# Generated by Django 4.2.5 on 2023-09-06 18:07

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_file_size],
            ),
        ),
    ]
